language: python
sudo: false

python:
    - "3.8"
    

addons:
  apt:
    packages:
      - libpcsclite-dev
      - swig

install:
    - pip install -r dev-requirements.txt
    - pip install .

script:
    - coverage run setup.py test

after_success:
    - coveralls
